import localFont from "next/font/local";
import "./globals.css";
import "./animations.css";

const galanoRegular = localFont({
  src: "./fonts/galano.woff",
  variable: "--font-galano-regular",
  weight: "100 900",
});

export const metadata = {
  title: "John Lloyd De Guzman",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`font-galano antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
